name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'vxibhxv' # Hashnode Username
          BLOG_URL: 'https://vxibhxv.hashnode.dev/' # Blog URL
          COUNT: 10 # MAX Visisble
        env:
           TOK_TOK: ${{ secrets.TOK_TOK }}
